### ISSUE TITLE
Retry Tenacity Error

### ISSUE THREAD

**Issue by sia-watsonlee** [koa-fin/sep#2]
I tried to run this code with my own open api key. but it results in this error:"
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}"

and then an exception to handle this error caused another RetryError as follows :"
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/sep/main.py", line 79, in <module>
    exp_model.train()
  File "/content/sep/exp/exp_model.py", line 22, in train
    data = self.dataloader.load(flag="train")
  File "/content/sep/data_load/dataloader.py", line 73, in load
    summary = self.summarizer.get_summary(ticker, tweet_data)
  File "/content/sep/summarize_module/summarizer.py", line 29, in get_summary
    summary = self.llm(prompt)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7a86b742f610 state=finished raised RateLimitError>]"

My Question is : do i have to buy Tier 1( or more) api key to resolve this problem ? or do i need to change the retryerror function !

**Comment by koa-fin** [comment]
You probably need to buy more credits or increase the spend limit on OpenAI.
You can track your API usage here: [https://platform.openai.com/usage](https://platform.openai.com/usage).
